# Generated by Django 4.2.4 on 2023-08-22 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="agegroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="batches",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batch_name", models.CharField(max_length=50)),
                ("batch_size", models.IntegerField()),
                ("timing", models.CharField(max_length=50)),
                ("days", models.CharField(max_length=50)),
                ("strength", models.IntegerField()),
                ("startdate", models.CharField(max_length=50)),
                ("teachername", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True)),
                (
                    "agegroup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agegroups",
                        to="batch.agegroup",
                    ),
                ),
            ],
        ),
    ]
