# Generated by Django 4.2.4 on 2023-08-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("batch", "0002_batches_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="agegroup",
            name="slug",
            field=models.SlugField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="batches",
            name="slug",
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
