# Generated by Django 4.2.4 on 2023-08-22 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("batch", "0004_days_teachers_timings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batches",
            name="days",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Days",
                to="batch.days",
            ),
        ),
        migrations.AlterField(
            model_name="batches",
            name="teachername",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Teachers",
                to="batch.teachers",
            ),
        ),
        migrations.AlterField(
            model_name="batches",
            name="timing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Timings",
                to="batch.timings",
            ),
        ),
    ]
