# Generated by Django 4.2.4 on 2023-08-28 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("batch", "0006_batches_vacancy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batches",
            name="vacancy",
            field=models.CharField(
                choices=[("FULL", "FULL"), ("VACANT", "VACANT")],
                default="VACANT",
                max_length=50,
            ),
        ),
    ]
